### ISSUE TITLE
milestone 1

### ISSUE THREAD

**Issue by tristanmkernan** [CodeAllianceOrg/odk2-json#2]
please also see https://github.com/CodeAllianceOrg/odk2/issues/6

## features

- [x] typescript library
- [x] test against benetech's odk2 converter
- [x] support sections
- [x] support text questions
- [x] import-able library
